databases:
  - name: youtubot_Database
    databaseName: youtubot
    user: youtubot
    region: singapore

services:
  - type: web
    name: youtubot_Backend
    runtime: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: youtubot
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4